# Generated by Django 4.2.28 on 2026-02-16 19:14

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_loan_workflow_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('documents_requested', 'Documents requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=api.models._default_token_expiry),
        ),
        migrations.CreateModel(
            name='ApplicationStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('documents_requested', 'Documents requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='api.loanapplication')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_applicationstatusupdate',
                'ordering': ['created_at'],
            },
        ),
    ]
