# Generated by Django 4.2.28 on 2026-02-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_application_status_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID or Passport'), ('proof_of_income', 'Proof of income / Bank statements'), ('land_certificate', 'Land certificate / Proof of land ownership'), ('marital_status_certificate', 'Marital status certificate (Irembo)'), ('recommendation_letter', 'Recommendation letter (local authority / subcommittee)'), ('proof_of_address', 'Proof of address'), ('spouse_id', 'Spouse ID (if married)')], max_length=40)),
                ('file', models.FileField(max_length=255, upload_to='loan_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.loanapplication')),
            ],
            options={
                'db_table': 'api_loanapplicationdocument',
                'ordering': ['document_type'],
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
