# Generated by Django 4.2.28 on 2026-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loan_application_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='farming_crops_or_activity',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='farming_estimated_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='farming_land_size_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='farming_livestock',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='farming_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='farming_season',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
