# Generated by Django 4.2.28 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_farming_fields_on_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='farmer_profiles/%Y/%m/'),
        ),
    ]
