# Generated by Django 5.0.14 on 2026-03-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_loan_application_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pay_frequency', models.CharField(blank=True, help_text='e.g. daily, weekly, monthly, per_season', max_length=20)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('status', models.CharField(default='active', help_text='active or inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_farmemployee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=150)),
                ('field_name', models.CharField(blank=True, max_length=150)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_name', models.CharField(blank=True, max_length=150)),
                ('seed_variety', models.CharField(blank=True, max_length=150)),
                ('seed_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seed_unit', models.CharField(blank=True, default='kg', max_length=20)),
                ('harvested_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('harvested_unit', models.CharField(blank=True, default='kg', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_productionrecord',
                'ordering': ['-planting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='kg', help_text='e.g. kg, bag, litre, piece', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_seedstock',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
