# Generated by Django 5.0.14 on 2026-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_farm_records_to_loan_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_photo_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_photo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
